name: ci
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-latest:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context:
          - tag: latest
            redis_version: latest
            redisai_version: latest
            redisearch_version: latest
            redisgraph_version: latest
            redistimeseries_version: latest
            rejson_version: latest
            rebloom_version: latest

          - tag: edge
            redis_version: latest
            redisai_version: edge-cpu-bionic
            redisearch_version: edge
            redisgraph_version: edge
            redistimeseries_version: edge
            rejson_version: edge
            rebloom_version: edge

    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Authenticate
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: rahilp/bitnami-redismod:${{ matrix.context.tag }}
          build-args: |
            redis_version=${{ matrix.context.redis_version }}
            redisai_version=${{ matrix.context.redisai_version }}
            redisearch_version=${{ matrix.context.redisearch_version }}
            redisgraph_version=${{ matrix.context.redisgraph_version }}
            redistimeseries_version=${{ matrix.context.redistimeseries_version }}
            rejson_version=${{ matrix.context.rejson_version }}
            rebloom_version=${{ matrix.context.rebloom_version }}
